on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: ${{ github.workspace }}/src
        run: go get -v -d all
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
      - name: Checkout CI-CD main
        uses: actions/checkout@v2
        with:
          repository: HyrenDev/CI-CD
          ref: v1
          token: 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
          path: .github/workflows
      - name: Deploy to all servers
        uses: .github/workflows