on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
      USERNAME: ${{ secrets.DEDICATED_1_HOST_USER }}
      PASSWORD: ${{ secrets.DEDICATED_1_PASSWORD }}
      PORT: ${{ secrets.DEDICATED_1_PORT }}
      PROJECT_FOLDER: ${{ github.workspace }}/src

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: ${{ github.workspace }}/src
        run: go get -v -d all
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
      - name: Deploy to all servers
        working-directory: ${{ github.workspace }}/src
        run: find ${{ github.workspace }}/src/nyrah # && sshpass -p $PASSWORD scp -P $PORT $PROJECT_FOLDER/nyrah $USERNAME@$HOST:/root/Nyrah
