on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: ${{ github.workspace }}/src
        run: go get -v -d all
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
      - name: Deploy to all servers
        uses: scp -o StrictHostKeyChecking=no -v -i -----BEGINRSAPRIVATEKEY-----MIIEowIBAAKCAQEAtvuzPSXUsrQjnUMLOIxAns8nT+xaxoHWuvz/2MrCJp34E3isJqd2yRGFMIUzbzOceN1ylQ7lVLZ4zys/zLM3846OqxxnlMicQ+AcMCGy06J/T+BABnGBgqgin4dsBdREXXOZn9200dQMBcVGomXiLyBEI1l0PYZ9o1Xuvgr44o817boHifgU6LZTPgrgLwCnp2Y1EqExYdGkY7f3TF01r/ZSKrawh2M71gRR1H4toFRRe7GuaFOZgxWsScjXGeP3vDUG2LYl+ilJHOfMQYOfF14ys7ReR2hKvvikd1VjSlkdVLro6ovmCYq7+JG2p1ynAtwnbbYZFd7eSD8D8+V5DQIDAQABAoIBAAEbwzkymng+qRyRxGaiSt3raVSNnPso3DEjyTT5/XUYbeFIUNqnFwwexAzIMciRqnf89225ul/p/w9aNre5ujQKgAi/Uk1Pbcrnd6Q/AANSL60/MYQYee1dsWAABQKAB639Pkf+otLGkxAR4tym+1jHvEHuj8qznt03bwvNqzZMHymeEvq/JpXjc9e4bImxLDDW2LuRP4e3h+E/pQXP1VO4gzSkzNmCsAjWk7fTmPvVq56ou52hzYkRr5R9zS5sXBCzsvJlJFKvYtBIcoSUnI0bPlYHERuNwCEG5E3RW+ZxYzaOx7SAV5eVHP0kSqOzw1vKsLXkzywPJOb1qmFj3G0CgYEA5/Heh9RpM6UI0OBehxm38KL/hWqbbseffGU3+ufv3kwEIWGdnJmJ+cjtdsg0v83HuXkegRBsYz2sKGDqLt5hpYFseX+Kfby/ej7GFCY2ymwgxjeQ+C9/m1xOctPFWJYFOKgYFHK+gEP2ncmTcwuMQ+Mb/sU9qL5p1Z7bVtwGX7MCgYEAyfXmuJICF2fDm2csgPz3ioQN+YupfFZy5lzz4ajfY0j3ZY+0KkxLCuamS6JUg3fZrl3qDYLWVph0DxR4++qOQhGqeKcjdMO6F02FJwAiL8XPhCtGIfxFvwFH9yVkX/NWDLCCay2dnpDkWqI89Ew9U0pHQCPxoCT0vIELHUJGZD8CgYEAlIjG2jNDv6fzUlgtENV+fuLTQaw4p6O81Zu4UryPVstVZc8ucOe+fTCYKZYieaYdPgB7cWmED7Wh9yXBMoyE+ck9Hz13AfiKoo1qqeKi+dRu1KEm/FjmniZpso09dvJzm4nCCe5FYryjRP6ep3EAvUTGW8wSJWrzObMGgcRbbJMCgYAGVS6Z5QIpx7grfE258bS1ZDSn+Ygj/PX3YTzIe6odi+EuDxaAKQpFWjwmrP1nbe+mdw1qxQqBhqBFBMhSZeV2DuXAiMUk2SpRpr2hHnDz/IjoRQ8a67UoKxsdlc+S7qdpGHPOdoy1tydh7CprIqTdorufOEFQWzhNXOKDVVutswKBgG/UvlRLOx0uA24tgIXthJvJ2RMGFxPciT4x8nc8EKc9DsTgealqSvC6ZVIokHg5mpw5YHpHiqOpNPCoNPeHQ1a8ABCPdrHTDJczDKpz10STNgoAHme6l8PLQuia+FjA/g7JJWlTVSx8ME6aLJVyxLvZ/eZ/5MO3KMgr5AU3ESmN-----ENDRSAPRIVATEKEY----- -P 22 -r $DIRECTORY/src/nyrah root@:149.56.242.214/root
        env:
          DIRECTORY: ${{ github.workspace }}
#        uses: nogsantos/scp-deploy@master
#        with:
#          src: ${{ github.workspace }}/src/nyrah
#          remote: /root
#          host: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
#          user: ${{ secrets.DEDICATED_1_HOST_USER }}
#          port: ${{ secrets.DEDICATED_1_PORT }}
#          key: ${{ secrets.DEDICATED_1_SSH_KEY }}