on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: ${{ github.workspace }}/src
        run: go get -v -d all
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
      - name: Deploy to all servers
        working-directory: ${{ github.workspace }}/src
        run: |
          sshpass -p $PASSWORD scp -P $PORT $DIRECTORY/src/nyrah $USER@:$HOST/root/Nyran
        env:
          DIRECTORY: ${{ github.workspace }}
          PASSWORD: ${{ secrets.DEDICATED_1_PASSWORD }}
          USER: ${{ secrets.DEDICATED_1_HOST_USER }}
          HOST: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
          PORT: ${{ secrets.DEDICATED_1_PORT }}