on: [ 'push' ]

env:
  WORKING_DIRECTORY: ${{ github.workspace }}/src

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: WORKING_DIRECTORY
        run: go get -v -d all
      - name: Build go project
        working-directory: WORKING_DIRECTORY
        run: go build
      - name: hyrendev/ci-cd@v1