on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: ${{ github.workspace }}/src
        run: go get -v -d all
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
      - name: Checkout CI-CD
        uses: nick-invision/private-action-loader@v3
        with:
          pal-repo-token: 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
          pal-repo-name: hyrendev/ci-cd