on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: ${{ github.workspace }}/src
        run: go get -v -d all
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
#      - name: Set up SSH key
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
#          username: ${{ secrets.USERNAME }}
#          key: ${{ secrets.DEDICATED_1_SSH_KEY }}
#          port: ${{ secrets.PORT }}
#          source: ${{ github.workspace }}/src
#          target: /root
      - name: Deploy to all servers
        uses: nogsantos/scp-deploy@master
        with:
          src: ${{ github.workspace }}/src
          host: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
          remote: /root
          user: ${{ secrets.DEDICATED_1_USER }}
          key: ${{ secrets.DEDICATED_1_SSH_KEY }}
          key_path: /root/.ssh