on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
      - name: Move generated file to output folder
        working-directory: ${{ github.workspace }}/src
        run: mv src Nyrah
#      - name: Deploy to dedicated
#        run: sshpass -p "$DEDICATED_1_PASSWORD" scp -P $DEDICATED_1_PORT /var/tmp/test $DEDICATED_1_HOST_USER@DEDICATED_1_HOST_ADDRESS:/root
#        env:
#          host: ${{ secrets.DEDICATED_1_HOST_ADDRESS }}
#          username: ${{ secrets.DEDICATED_1_HOST_USER }}
#          password: ${{ secrets.DEDICATED_1_PASSWORD }}
#          port: ${{ secrets.DEDICATED_1_PORT }}
