on: [ 'push' ]

jobs:
  nyrah-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update branch to latest
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.3
      - name: Download dependencies
        working-directory: ${{ github.workspace }}/src
        run: go get -v -d all
      - name: Build go project
        working-directory: ${{ github.workspace }}/src
        run: go build
      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEDICATED_1_SSH_KEY }}
      - name: Deploy to all servers
        run: scp ${{ github.workspace }}/src/nyrah ${{ secrets.DEDICATED_1_USER }}@${{ secrets.DEDICATED_1_HOST }}:/root
#      - name: Deploy to all servers
#        uses: nogsantos/scp-deploy@master
#        with:
#          src: ${{ github.workspace }}/src
#          host: ${{ DEDICATED_1_HOST_ADDRESS }}
#          remote: /root
#          user: ${{ DEDICATED_1_USER }}
#          key: ${{ secrets.DEDICATED_1_SSH_KEY }}