on: [ 'push' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up go
      uses: actions/setup-go@v2
    - name: Build go project
      run: go build /etc/actions-runner/_work/s.Nyrah/s.Nyrah/src
    - name: Move generated file to output folder
      run: mv /etc/actions-runner/_work/s.Nyrah/s.Nyrah/src /home/cloud/output/Nyrah
