on: [ 'push' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.3'
    - name: Build go project
      run: go build
    - name: 'Display project folder'
      run: echo 'Primeiro >> {GITHUB_REPOSITORY}' && echo 'Segundo >> ${GITHUB_REPOSITORY}'
