on: [ 'push' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up go
      uses: actions/setup-go@v2
    - name: Checkout project folder
      run: cd ${GITHUB_WORKSPACE}/src/
    - name: Build go project
      run: go build
    - name: Move generated file to output folder
      run: mv src /home/cloud/output/Nyrah
