on: [ 'push' ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up go
      uses: actions/setup-go@v2
    - name: Build go project
      run: cd /etc/actions-runner/_work/s.Nyrah/s.Nyrah/ && go build src
    - name: Move generated file to output folder
      run: cd /etc/actions-runner/_work/s.Nyrah/s.Nyrah/ && mv src /home/cloud/output/Nyrah
